"""
Minimal HHG analysis placeholder for the Fortran workflow.
This mirrors the Python HHG_spectra_analysis folder and is intended to load the
Fortran time-evolution output file generated by vector_time_evolution.f90.
"""

import numpy as np
from pathlib import Path


def load_evo_data(path):
    path = Path(path)
    data = np.loadtxt(path, skiprows=1)
    if data.ndim == 1:
        data = data.reshape(1, -1)
    return data


if __name__ == '__main__':
    evo_file = Path(__file__).resolve().parent.parent / 'Time_evolution_data'
    files = sorted(evo_file.glob('*.dat'))
    if not files:
        print('No time-evolution .dat files found in ./Time_evolution_data')
        raise SystemExit(0)

    data = load_evo_data(files[0])
    print(f'Loaded: {files[0].name}')
    print(f'shape = {data.shape}')
    print('Columns: t, E(t), d(t), Ps(t)')
