"""
File: HHG_spectra_fortran_as_python.py

HHG spectra analysis for time-evolution data generated by the Fortran
workflow, processed in exactly the same way as the Python-generated
time-evolution data.

Expected data columns:
    column 0 : time t (a.u.)
    column 1 : electric field E(t) (a.u.)
    column 2 : dipole moment d(t) (a.u.)
    column 3 : survival probability Ps(t)

The spectral calculation, normalization, conversion efficiency and
attosecond-pulse spectral gating follow the Python HHG_spectra.py workflow.
"""

import argparse
import numpy as np
from pathlib import Path
import scipy.fft as ft
import matplotlib.pyplot as plt


# ============================================================
#                 Laser parameters
# ============================================================

# Fundamental laser frequency used in the calculation.
# Change this to the value used in your Fortran simulation.
w0 = 0.057       # a.u.

T = 2 * np.pi / w0


# ============================================================
#                 Figure settings
# ============================================================

width = 6.2
height = 4
fig_scale_factor = 2
fig_size = (fig_scale_factor * width,
            fig_scale_factor * height)

plt.rc('font', family='serif', size=14)


# ============================================================
#                    Load evolution data
# ============================================================

def load_evo_data(path):
    """
    Load Fortran-generated time-evolution data.

    The file is expected to contain one header line followed by
    numerical columns:
        t, E(t), d(t), Ps(t)
    """
    path = Path(path)

    data = np.loadtxt(path, skiprows=1)

    if data.ndim == 1:
        data = data.reshape(1, -1)

    if data.shape[1] < 4:
        raise ValueError(
            f"Expected at least 4 columns in {path.name}, "
            f"but found {data.shape[1]}."
        )

    return data


# ============================================================
#                     Main calculation
# ============================================================

def calculate_hhg(data, w0):
    """
    Calculate HHG quantities using the same procedure as the
    Python-generated data analysis.

    IMPORTANT:
    dt and tf are obtained from the actual time array rather than
    assuming a Python-specific value.
    """

    # --------------------------------------------------------
    # Extract columns
    # --------------------------------------------------------

    t = data[:, 0]
    E_t = data[:, 1]
    dipole_moment = data[:, 2]
    survival_probability = data[:, 3]

    # --------------------------------------------------------
    # Time information
    # --------------------------------------------------------

    dt_array = np.diff(t)

    if len(dt_array) == 0:
        raise ValueError("Time array contains fewer than two points.")

    dt = np.mean(dt_array)

    # Check whether the Fortran output is uniformly sampled.
    if not np.allclose(dt_array, dt, rtol=1e-8, atol=1e-12):
        raise ValueError(
            "Time grid is not uniformly sampled. "
            "FFT requires a uniformly sampled time grid."
        )

    # Use the actual duration represented by the data.
    #
    # This matches the intended Python workflow while avoiding
    # dependence on a hard-coded Fortran/Python tf.
    tf = t[-1] - t[0]

    if tf <= 0:
        raise ValueError("Total evolution time must be positive.")

    # --------------------------------------------------------
    # HHG spectrum
    # --------------------------------------------------------

    dipole_mom_FFT = ft.fft(dipole_moment)

    freq_w = ft.fftfreq(
        len(t),
        d=dt
    ) * 2 * np.pi

    dip_mom_power_spectra_full = np.abs(
        dipole_mom_FFT / tf
    )**2

    # Positive frequencies only
    positive_freq_mask = freq_w > 0

    freq_pos = freq_w[positive_freq_mask]

    dip_mom_power_spectra = \
        dip_mom_power_spectra_full[positive_freq_mask]

    # Harmonic order
    harmonic_order = freq_pos / w0

    # --------------------------------------------------------
    # Conversion efficiency
    # --------------------------------------------------------

    harmonic_energy = np.trapezoid(
        dip_mom_power_spectra,
        freq_pos
    )

    laser_energy = np.trapezoid(
        E_t**2,
        t
    )

    eta = harmonic_energy / laser_energy

    # --------------------------------------------------------
    # Attosecond pulse via spectral gating
    # --------------------------------------------------------

    # Dipole acceleration spectrum.
    accel_FFT = -(freq_w**2) * dipole_mom_FFT

    harm_min, harm_max = 15, 45

    def soft_gate(mask_freqs, lo, hi, order=6):
        center = (lo + hi) / 2
        width = (hi - lo) / 2
        return np.exp(
            -((np.abs(mask_freqs) - center) / width)**order
        )

    harmonic_orders_full = freq_w / w0

    gate = soft_gate(
        harmonic_orders_full,
        harm_min,
        harm_max,
        order=6
    )

    accel_gated = accel_FFT * gate

    # Back to time domain
    a_t_gated = ft.ifft(accel_gated)

    attosecond_intensity = np.abs(a_t_gated)**2

    # Normalize for plotting
    max_intensity = attosecond_intensity.max()

    if max_intensity > 0:
        attosecond_intensity /= max_intensity

    return {
        "t": t,
        "E_t": E_t,
        "dipole_moment": dipole_moment,
        "survival_probability": survival_probability,
        "dt": dt,
        "tf": tf,
        "freq_w": freq_w,
        "freq_pos": freq_pos,
        "harmonic_order": harmonic_order,
        "dip_mom_power_spectra": dip_mom_power_spectra,
        "harmonic_energy": harmonic_energy,
        "laser_energy": laser_energy,
        "eta": eta,
        "attosecond_intensity": attosecond_intensity,
        "harm_min": harm_min,
        "harm_max": harm_max,
    }


# ============================================================
#                         Main
# ============================================================

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description="HHG spectra analysis for Fortran-generated data."
    )

    parser.add_argument(
        "file",
        nargs="?",
        help="Fortran time-evolution .dat file"
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # Locate data file
    # --------------------------------------------------------

    if args.file is not None:
        evo_file = Path(args.file).resolve()

    else:
        evo_dir = (
            Path(__file__).resolve().parent.parent
            / "Time_evolution_data"
        )

        files = sorted(evo_dir.glob("*.dat"))

        if not files:
            print(
                "No time-evolution .dat files found in "
                "./Time_evolution_data"
            )
            raise SystemExit(0)

        evo_file = files[0]

    # --------------------------------------------------------
    # Load and calculate
    # --------------------------------------------------------

    data = load_evo_data(evo_file)

    result = calculate_hhg(data, w0)

    t = result["t"]
    E_t = result["E_t"]
    dipole_moment = result["dipole_moment"]
    survival_probability = result["survival_probability"]

    dt = result["dt"]
    tf = result["tf"]

    freq_pos = result["freq_pos"]
    harmonic_order = result["harmonic_order"]
    dip_mom_power_spectra = result["dip_mom_power_spectra"]

    harmonic_energy = result["harmonic_energy"]
    laser_energy = result["laser_energy"]
    eta = result["eta"]

    attosecond_intensity = result["attosecond_intensity"]
    harm_min = result["harm_min"]
    harm_max = result["harm_max"]

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print(f"Loaded: {evo_file.name}")
    print(f"Data shape                         : {data.shape}")

    print("\n~~~~~~~~~~~: Time Evolution Summary :~~~~~~~~~~~")
    print(f" Number of time points (len(t))    : {len(t)}")
    print(f" Time step (dt)                    : {dt:.8f} a.u.")
    print(f" Total evolution time (tf)         : {tf:.8f} a.u.")
    print(f" Fundamental frequency (ω₀)        : {w0:.5f} a.u.")
    print(f" Optical period (T)                : {T:.5f} a.u.")
    print(f" Max frequency (Nyquist, ω_max)    : {freq_pos[-1]:.5f} a.u.")

    print("\n~~~~~~~~~~~~: Conversion efficiency :~~~~~~~~~~~~")
    print(f" Total laser energy (∫E² dt)       : {laser_energy:.6e}")
    print(f" Total harmonic energy (∫P(ω) dω) : {harmonic_energy:.6e}")
    print(f" Conversion efficiency (eta)       : {eta:.6e}")


    # ========================================================
    #                         Figures
    # ========================================================

    fig1 = plt.figure(figsize=fig_size)
    fig2 = plt.figure(figsize=fig_size)
    fig3 = plt.figure(figsize=fig_size)

    # Figure 1
    ax1 = fig1.add_subplot(211)
    ax2 = fig1.add_subplot(212)

    # Figure 2
    ax3 = fig2.add_subplot(211)
    ax4 = ax3.twinx()
    ax5 = fig2.add_subplot(223)
    ax6 = fig2.add_subplot(224)

    # Figure 3
    ax7 = fig3.add_subplot(111)


    # ========================================================
    #                         Plots
    # ========================================================

    # Dipole moment
    ax1.plot(
        t / T,
        dipole_moment,
        color='#7F3FBF',
        lw=2,
        label='d(t)'
    )

    # HHG spectrum
    # Clip zero/underflow values so log10 does not generate
    # unnecessary warnings.
    positive_power = dip_mom_power_spectra > 0

    ax2.plot(
        harmonic_order[positive_power],
        np.log10(dip_mom_power_spectra[positive_power]),
        color='#2CA02C',
        label=r'log$_{10}$[P($\omega$)]'
    )

    # Electric field
    ax3.plot(
        t / T,
        E_t,
        label='E(t)'
    )

    # Survival probability on secondary axis
    ax4.plot(
        t / T,
        survival_probability,
        color='m',
        label=r'P$_s$(t)'
    )

    # Survival probability
    ax5.plot(
        t / T,
        survival_probability,
        color='limegreen',
        lw=2,
        label=r'P$_s$(t)'
    )

    # Ionisation probability
    ionisation_probability = 1 - survival_probability

    ax6.plot(
        t / T,
        ionisation_probability,
        color='crimson',
        lw=2,
        label=r'P$_i$(t)'
    )

    # Attosecond pulse
    ax7.plot(
        t / T,
        attosecond_intensity,
        color='crimson',
        lw=1.5,
        label=f'Gated harmonics {harm_min}-{harm_max}'
    )


    # ========================================================
    #                         Labels
    # ========================================================

    ax1.set_ylabel('d(t)', fontsize=15)
    ax1.set_xlabel('Optical cycles (t/T)', fontsize=15)

    ax2.set_xlabel(
        r'Harmonic Order (ω/ω$_0$)',
        fontsize=15
    )
    ax2.set_ylabel(
        r'log$_{10}$[P($\omega$)]',
        fontsize=15
    )

    ax3.set_xlabel('Optical cycles (t/T)', fontsize=15)
    ax5.set_xlabel('Optical cycles (t/T)', fontsize=15)
    ax6.set_xlabel('Optical cycles (t/T)', fontsize=15)
    ax7.set_xlabel('Optical cycles (t/T)', fontsize=15)

    ax3.set_ylabel('E(t) (a.u.)', fontsize=15)
    ax4.set_ylabel(r'P$_s$(t) (a.u.)', fontsize=15)
    ax5.set_ylabel(r'P$_s$(t) (a.u.)', fontsize=15)
    ax6.set_ylabel(r'P$_i$(t) (a.u.)', fontsize=15)
    ax7.set_ylabel(
        'Attosecond pulse intensity (norm.)',
        fontsize=15
    )


    # ========================================================
    #                         Legends
    # ========================================================

    ax1.legend(
        loc='upper right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax2.legend(
        loc='upper right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax3.legend(
        loc='upper right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax4.legend(
        loc='lower left',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax5.legend(
        loc='upper right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax6.legend(
        loc='lower right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )

    ax7.legend(
        loc='upper right',
        fontsize=14,
        framealpha=0.5,
        edgecolor='w'
    )


    # ========================================================
    #                         Limits
    # ========================================================

    ax1.set_xticks(np.arange(0, 61, 5))

    ax2.set_yticks(np.arange(-20, -2, 4))
    ax2.set_xticks(
        np.arange(1, int(max(harmonic_order)), 4)
    )
    ax2.set_xlim(
        -1,
        min(102, harmonic_order[-1])
    )

    ax1.set_ylim(
        1.5 * min(dipole_moment),
        1.5 * max(dipole_moment)
    )

    ax5.set_ylim(0, 1.05)
    ax6.set_ylim(0, 1.05)

    ax6.yaxis.set_label_position('right')
    ax6.yaxis.tick_right()


    # ========================================================
    #                         Titles
    # ========================================================

    fig1.suptitle(evo_file.name, fontsize=12)
    fig2.suptitle(evo_file.name, fontsize=12)
    fig3.suptitle(evo_file.name, fontsize=12)

    fig1.subplots_adjust(
        top=0.94,
        bottom=0.084,
        left=0.079,
        right=0.98,
        hspace=0.195,
        wspace=0.2
    )

    fig2.subplots_adjust(
        top=0.94,
        bottom=0.084,
        right=0.92,
        left=0.08,
        hspace=0.195,
        wspace=0.074
    )

    plt.show()
