"""
File: Atto_pulse.py
Project: HHG-SaDAS
Code Description:
    *** [Main Attosecond Pulse generating code] ***
    This script reads the time-evolution data generated by `time_evolution.py`,
    calculates the High-Harmonic Generation (HHG) spectra from the dipole moment
    data, and reconstructs the attosecond pulse (train) via spectral gating of
    the dipole acceleration spectrum.

    It also provides an interactive GUI (compact numeric textbox controls +
    a zoom range-slider on the RHS) to:
        - Tune the spectral selection gate (harmonic range + smoothness/order)
        - Zoom into a region of the reconstructed attosecond pulse profile
        - Overlay a manually adjustable Gaussian (position, width, height)
          for visual pulse-duration comparison

    Callbacks are split by cost (gate recompute vs. zoom vs. Gaussian overlay)
    so that dragging the zoom slider or editing the Gaussian only redraws the
    cheap parts of the figure instead of re-running the FFT/iFFT gating pipeline.

Author: Siddhartha Mithiya
Affiliation: Indian Institute of Technology (IIT) Mandi
License: MIT License
Repository: https://github.com/Siddhartha-Acad/HHG-SaDAS.git

--------------------------------------------------------------------------------
Notes:
- This file is part of the HHG-SaDAS package, developed during my MS(R) thesis:
  "Higher-Order Harmonic Generation and Harmonic-Power Enhancement in Noble-Gas Atoms Confined Inside C60".
--------------------------------------------------------------------------------
"""

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))   # Ensure project root (HHG-SaDAS) is in sys.path

import argparse
import numpy as np
import pandas as pd
import scipy.fft as ft
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox, Button, RangeSlider
from Assistant.Decorate_axes import decorate_axes_L as da
from Harmonic_generation_py.parameters import (
    confined, time_step, evolving_atom, state_symb, m, SAE_model,
    L, k_max, N, r_max, L_map, conf_model, WHITE, RESET,
    dt, tf, w0, T,
)
from Harmonic_generation_py.functions import (
    print_grid_info, print_smat_info, print_atom_info, print_laser_info,
)

parser = argparse.ArgumentParser()
parser.add_argument('-A', '--auto', action='store_true', help='enable automatic input time evolution data')
parser.add_argument('-v', action='store_true', help='verbose mode')
args = parser.parse_args()

if not args.v:
    print_grid_info()
    print_smat_info()
    print_atom_info()
    print_laser_info()
else:
    pass

# ~~~~~~~~~~~~~~~~~~~~~~: Common Figure Settings :~~~~~~~~~~~~~~~~~~~~
width = 6.2                         # Width in inches
height = 4                          # Height in inches
fig_scale_factor = 2                # big=2 ; medium=1.5; small=1
fig_size = (fig_scale_factor*width, fig_scale_factor*height)

plt.rc('font', **{'family': 'serif', 'size': 12})
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                Import and read time evolution data                 |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
this_dir = Path(__file__).resolve().parent

if args.auto:
    if not confined:
        evo_data_file = f'VEvo_nopt={time_step}_{evolving_atom}({state_symb})_m={m}_{SAE_model}_L={L}_kmax={k_max}_N={N}_rmax={r_max}_Lmap={L_map}_dt={dt}.dat'
    else:
        evo_data_file = f'VEvo_nopt={time_step}_{evolving_atom}({state_symb})@C60_m={m}_{SAE_model}_{conf_model}_L={L}_kmax={k_max}_N={N}_rmax={r_max}_Lmap={L_map}_dt={dt}.dat'
else:
    evo_data_file = 'Evo_nopt=88036_H(1s)_m=0_SAE-M1_L=20_kmax=50_N=200_rmax=200_Lmap=80_dt=0.1.dat'

evo_data_path = this_dir.parent / 'Time_evolution_data' / f'{evo_data_file}'
evo_data = np.loadtxt(evo_data_path, skiprows=1)

t = evo_data[:, 0]                         # time                       : (a.u.)
E_t = evo_data[:, 1]                       # Electric field             : (a.u.)
dipole_moment = evo_data[:, 2]             # dipole moment d(t)         : (a.u.)
survival_probability = evo_data[:, 3]      # survival probability ps(t) : (a.u.)



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                    Calculating the HHG Spectra                     |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dipole_mom_FFT = ft.fft(dipole_moment)
freq_w = ft.fftfreq(len(t), d=dt) * 2 * np.pi                   # Nyquist Angular frequency (omega -> w).
dip_mom_power_spectra = np.abs(dipole_mom_FFT / tf)**2          # Harmonic power spectra.

positive_freq_mask = freq_w > 0             # positive angular frequency mask: returns a boolean array where True corresponds to freq_w > 0
freq_pos = freq_w[positive_freq_mask]       # Positive Nyquist frequencies.

harmonic_order = freq_pos / w0                                          # Harmonic Order (w/w0)
dip_mom_power_spectra = dip_mom_power_spectra[positive_freq_mask]       # P(w) : The power spectra you want!



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                       Conversion efficiency                        |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
harmonic_energy = np.trapezoid(dip_mom_power_spectra, freq_pos)
laser_energy = np.trapezoid(E_t**2, t)

eta = harmonic_energy / laser_energy

print(f" {WHITE}~~~~~~~~~~~: Harmonic Spectra Summary :~~~~~~~~~~{RESET}")
print(f" Number of time points (len(t))   : {len(t)}")
print(f" Time step (dt)                   : {dt} a.u.")
print(f" Fundamental frequency (ω₀)       : {w0:.5f} a.u.")
print(f" Max frequency (Nyquist, ω_max)   : {freq_pos[-1]:.5f} a.u.", '\n')

print(f" {WHITE}~~~~~~~~~~~~: Conversion efficiency :~~~~~~~~~~~~{RESET}")
print(f" Total laser energy (∫E² dt)      : {laser_energy:.6e}")
print(f" Total harmonic energy (∫P(ω) dω) : {harmonic_energy:.6e}")
print(f" Conversion efficiency (eta)      : {eta:.6e}")



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#              Attosecond pulse via spectral gating                  |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
accel_FFT = -(freq_w**2) * dipole_mom_FFT   # Dipole acceleration spectrum (physically radiated quantity)
harmonic_orders_full = freq_w / w0          # Harmonic order axis (signed, +/- branches)
t_over_T = t / T                            # precompute once, reused by both the pulse and Gaussian overlay

# Initial gate / GUI default values
harm_min_0, harm_max_0 = 15.0, 45.0
gate_order_0 = 20
t_min_T, t_max_T = float(t.min()/T), float(t.max()/T)
zoom_min_0, zoom_max_0 = t_min_T, t_max_T
gauss_pos_0    = (t_min_T + t_max_T) / 2
gauss_width_0  = 0.05
gauss_height_0 = 1.0

# Soft-edged window (super-Gaussian) instead of a hard cutoff,
# to avoid ringing artifacts from an abrupt spectral edge.
# Evaluated on |freq_w|/w0 so it's symmetric for +/- frequencies,
# which keeps a_t_gated real after the inverse FFT.
def soft_gate(mask_freqs, lo, hi, order=6):
    center = (lo + hi) / 2
    width  = (hi - lo) / 2
    return np.exp(-((np.abs(mask_freqs) - center) / width)**order)

def compute_pulse(lo, hi, order):
    """Recompute gate + gated acceleration spectrum + attosecond pulse for given (lo, hi, order)."""
    gate = soft_gate(harmonic_orders_full, lo, hi, order)
    accel_gated = accel_FFT * gate
    a_t_gated = ft.ifft(accel_gated)
    intensity = np.abs(a_t_gated)**2
    intensity /= intensity.max()
    return gate, intensity

gate, attosecond_intensity = compute_pulse(harm_min_0, harm_max_0, gate_order_0)
gate_pos = gate[positive_freq_mask]         # Gate values on the positive-frequency axis (for overlay on HHG spectrum)



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                         Interactive Plotting                       |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fig1 = plt.figure(figsize=fig_size)
gs = fig1.add_gridspec(2, 1, top=0.94, bottom=0.08, left=0.08, right=0.68, hspace=0.35)

ax2 = fig1.add_subplot(gs[0])         # HHG spectra
ax2b = ax2.twinx()                    # Spectral selection gate (0-1, right axis)
ax7 = fig1.add_subplot(gs[1])         # Attosecond pulse intensity
da.decorate_2d([ax2, ax7])
da.decorate_2d(ax2b, visible_spine='none', grid=False)

spec_line, = ax2.plot(harmonic_order, np.log10(dip_mom_power_spectra), color='#2CA02C', label=r'log$_{10}$[P($\omega$)]')
gate_line,  = ax2b.plot(harmonic_order, gate_pos, color='dimgray', ls='--', lw=1.5)
atto_line,  = ax7.plot(t_over_T, attosecond_intensity, color='crimson', lw=1.5)
gauss_line, = ax7.plot([], [], color='dodgerblue', ls='--', lw=1.5, label='Gaussian fit')

ax2.set_yticks(np.arange(-20, -2, 4))                               # Some controls
ax2.set_xticks(np.arange(1, int(max(harmonic_order)), 4))           # over
ax2.set_xlim(-1, 102)                                                # HHG spectra plot.
ax2b.set_ylim(0, 1.05)
ax2b.set_yticks([])

ax2.set_xlabel(r'Harmonic Order (ω/ω$_0$)', fontsize=12)
ax2.set_ylabel(r'log$_{10}$[P($\omega$)]', fontsize=12)

ax7.set_xlabel('optical cycles (t/T)', fontsize=12)
ax7.set_ylabel('Attosecond pulse intensity (norm.)', fontsize=12)
ax7.set_xlim(zoom_min_0, zoom_max_0)
ax7.set_ylim(-0.05, 1.4)

# Legends created once (no dynamic label text) -> not rebuilt on every callback
ax2.legend(loc='upper right', fontsize=11, framealpha=0.5, edgecolor='w')
ax7.legend(loc='upper right', fontsize=11, framealpha=0.5, edgecolor='w')

fig1.suptitle(evo_data_file, fontsize=12)


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#              GUI controls (compact RHS textboxes + slider)         |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
panel_x0, panel_w = 0.78, 0.12          # narrower boxes than before
box_h, box_gap = 0.022, 0.032           # smaller box height, tighter vertical spacing

def pad(val):
    """Left-pad the displayed value so digits don't touch the textbox border."""
    return f'   {val}'

def add_labeled_box(y, label, initial):
    fig1.text(panel_x0 - 0.02, y + box_h/2, label, ha='right', va='center', fontsize=10)
    box_ax = fig1.add_axes([panel_x0, y, panel_w, box_h])
    return TextBox(box_ax, '', initial=pad(initial))

# Section: spectral gate
y = 0.90
fig1.text(panel_x0, y, 'Spectral gate', fontsize=12, fontweight='bold'); y -= box_gap
tb_harm_min = add_labeled_box(y, 'Harm. min',  harm_min_0);  y -= box_gap
tb_harm_max = add_labeled_box(y, 'Harm. max',  harm_max_0);  y -= box_gap
tb_order    = add_labeled_box(y, 'Smoothness', gate_order_0); y -= box_gap*1.4

# Section: pulse zoom (textboxes + range-slider underneath)
fig1.text(panel_x0, y, 'Pulse zoom (t/T)', fontsize=12, fontweight='bold'); y -= box_gap
tb_zoom_min = add_labeled_box(y, 'Zoom min', f'{zoom_min_0:.3f}'); y -= box_gap
tb_zoom_max = add_labeled_box(y, 'Zoom max', f'{zoom_max_0:.3f}'); y -= box_gap*0.9

ax_zoom_slider = fig1.add_axes([panel_x0, y, panel_w, 0.018])
zoom_slider = RangeSlider(ax_zoom_slider, '', t_min_T, t_max_T, valinit=(zoom_min_0, zoom_max_0))
zoom_slider.valtext.set_visible(False)                          # keep it compact; textboxes show the numbers
y -= box_gap*1.5

# Section: Gaussian overlay
fig1.text(panel_x0, y, 'Gaussian overlay', fontsize=12, fontweight='bold'); y -= box_gap
tb_gauss_pos    = add_labeled_box(y, 'Position', f'{gauss_pos_0:.3f}'); y -= box_gap
tb_gauss_width  = add_labeled_box(y, 'Width',    gauss_width_0);        y -= box_gap
tb_gauss_height = add_labeled_box(y, 'Height',   gauss_height_0);       y -= box_gap*1.4

ax_apply = fig1.add_axes([panel_x0, y, panel_w*0.48, 0.045])
ax_reset = fig1.add_axes([panel_x0 + panel_w*0.52, y, panel_w*0.48, 0.045])
apply_button = Button(ax_apply, 'Apply')
reset_button = Button(ax_reset, 'Reset')


def _to_float(textbox, fallback):
    try:
        return float(textbox.text)         # float() tolerates the leading padding spaces
    except ValueError:
        textbox.set_val(pad(fallback))     # revert invalid entry
        return fallback


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     Split, cost-aware callbacks: only recompute what actually       |
#     changed, so slider dragging / textbox edits stay responsive.    |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def update_gate(_event=None):
    """Expensive: re-runs the FFT-based gating pipeline. Only call on gate-param changes."""
    lo    = _to_float(tb_harm_min, harm_min_0)
    hi    = _to_float(tb_harm_max, harm_max_0)
    order = _to_float(tb_order, gate_order_0)

    gate, intensity = compute_pulse(lo, hi, order)
    gate_line.set_ydata(gate[positive_freq_mask])
    atto_line.set_ydata(intensity)
    fig1.canvas.draw_idle()


def update_zoom(_event=None):
    """Cheap: only changes the pulse-axis x-limits."""
    zlo = _to_float(tb_zoom_min, zoom_min_0)
    zhi = _to_float(tb_zoom_max, zoom_max_0)
    ax7.set_xlim(zlo, zhi)
    fig1.canvas.draw_idle()


def update_gaussian(_event=None):
    """Cheap: only recomputes the overlaid Gaussian curve."""
    pos     = _to_float(tb_gauss_pos, gauss_pos_0)
    gwidth  = _to_float(tb_gauss_width, gauss_width_0)
    gheight = _to_float(tb_gauss_height, gauss_height_0)
    gauss_line.set_data(t_over_T, gheight * np.exp(-0.5 * ((t_over_T - pos) / gwidth) ** 2))
    fig1.canvas.draw_idle()


def sync_zoom_from_slider(val):
    """Slider drag -> push values into the zoom textboxes (no float-parsing needed), then redraw xlim only."""
    zlo, zhi = val
    tb_zoom_min.eventson, tb_zoom_max.eventson = False, False
    tb_zoom_min.set_val(pad(f'{zlo:.3f}'))
    tb_zoom_max.set_val(pad(f'{zhi:.3f}'))
    tb_zoom_min.eventson, tb_zoom_max.eventson = True, True
    ax7.set_xlim(zlo, zhi)
    fig1.canvas.draw_idle()


def sync_zoom_from_textbox(_event=None):
    """Textbox edit -> push values into the slider (without recursing), then redraw xlim only."""
    zlo = _to_float(tb_zoom_min, zoom_min_0)
    zhi = _to_float(tb_zoom_max, zoom_max_0)
    zoom_slider.eventson = False
    zoom_slider.set_val((zlo, zhi))
    zoom_slider.eventson = True
    ax7.set_xlim(zlo, zhi)
    fig1.canvas.draw_idle()


def apply_all(_event=None):
    update_gate()
    update_zoom()
    update_gaussian()


def reset(_event=None):
    tb_harm_min.set_val(pad(harm_min_0))
    tb_harm_max.set_val(pad(harm_max_0))
    tb_order.set_val(pad(gate_order_0))
    tb_zoom_min.set_val(pad(f'{zoom_min_0:.3f}'))
    tb_zoom_max.set_val(pad(f'{zoom_max_0:.3f}'))
    zoom_slider.eventson = False
    zoom_slider.set_val((zoom_min_0, zoom_max_0))
    zoom_slider.eventson = True
    tb_gauss_pos.set_val(pad(f'{gauss_pos_0:.3f}'))
    tb_gauss_width.set_val(pad(gauss_width_0))
    tb_gauss_height.set_val(pad(gauss_height_0))
    apply_all()


# Each control only triggers the callback that actually needs to run
tb_harm_min.on_submit(update_gate)
tb_harm_max.on_submit(update_gate)
tb_order.on_submit(update_gate)

tb_zoom_min.on_submit(sync_zoom_from_textbox)
tb_zoom_max.on_submit(sync_zoom_from_textbox)
zoom_slider.on_changed(sync_zoom_from_slider)

tb_gauss_pos.on_submit(update_gaussian)
tb_gauss_width.on_submit(update_gaussian)
tb_gauss_height.on_submit(update_gaussian)

apply_button.on_clicked(apply_all)
reset_button.on_clicked(reset)

apply_all()   # draw everything once at startup

plt.show()