"""
File: Atto_pulse.py
Project: HHG-SaDAS
Code Description:
    *** [Main Attosecond Pulse generating code] ***
    This script reads the time-evolution data generated by `time_evolution.py`,
    calculates the High-Harmonic Generation (HHG) spectra from the dipole moment
    data, and reconstructs the attosecond pulse (train) via spectral gating of
    the dipole acceleration spectrum.

    It also provides an interactive GUI (compact numeric textbox controls +
    coarse/fine zoom range-sliders on the RHS) to:
        - Tune the spectral selection gate (harmonic range + smoothness/order)
        - Zoom into a region of the reconstructed attosecond pulse profile,
          coarsely first, then fine-tune within that coarse window
        - Fit N Gaussians to the distinct burst(s) inside the zoomed window
          (low-amplitude ringing is ignored via a peak-prominence filter),
          each drawn in its own color, and report each peak's position (t/T)
          and FWHM (attoseconds)

    Callbacks are split by cost (gate recompute vs. zoom vs. Gaussian fit)
    so that dragging either zoom slider stays responsive instead of
    re-running the FFT/iFFT gating pipeline on every event.

Author: Siddhartha Mithiya
Affiliation: Indian Institute of Technology (IIT) Mandi
License: MIT License
Repository: https://github.com/Siddhartha-Acad/HHG-SaDAS.git

--------------------------------------------------------------------------------
Notes:
- This file is part of the HHG-SaDAS package, developed during my MS(R) thesis:
  "Higher-Order Harmonic Generation and Harmonic-Power Enhancement in Noble-Gas Atoms Confined Inside C60".
--------------------------------------------------------------------------------
"""

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))   # Ensure project root (HHG-SaDAS) is in sys.path

import argparse
import numpy as np
import pandas as pd
import scipy.fft as ft
from scipy.signal import find_peaks
from scipy.optimize import curve_fit
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox, Button, RangeSlider
from matplotlib.patches import Rectangle
from Assistant.Decorate_axes import decorate_axes_L as da
from Harmonic_generation_py.parameters import (
    confined, time_step, evolving_atom, state_symb, m, SAE_model,
    L, k_max, N, r_max, L_map, conf_model, WHITE, RESET,
    dt, tf, w0, T,
)
from Harmonic_generation_py.functions import (
    print_grid_info, print_smat_info, print_atom_info, print_laser_info,
)

parser = argparse.ArgumentParser()
parser.add_argument('-A', '--auto', action='store_true', help='enable automatic input time evolution data')
parser.add_argument('-v', action='store_true', help='verbose mode')
args = parser.parse_args()

if not args.v:
    print_grid_info()
    print_smat_info()
    print_atom_info()
    print_laser_info()
else:
    pass

# ~~~~~~~~~~~~~~~~~~~~~~: Common Figure Settings :~~~~~~~~~~~~~~~~~~~~
width = 6.2                         # Width in inches
height = 4                          # Height in inches
fig_scale_factor = 2                # big=2 ; medium=1.5; small=1
fig_size = (fig_scale_factor*width, fig_scale_factor*height)

plt.rc('font', **{'family': 'serif', 'size': 12})

AU_TO_AS = 24.18884326              # 1 atomic unit of time, in attoseconds
GAUSS_COLORS = ['#0072B2', '#009E73', '#F0A500', '#8E44AD',
                 '#00BFC4', '#3D5A80', '#E69F00', '#5D3FD3']    # one per fitted peak, cycled if >8 (no red - pulse curve is already crimson)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                Import and read time evolution data                 |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
this_dir = Path(__file__).resolve().parent

if args.auto:
    if not confined:
        evo_data_file = f'VEvo_nopt={time_step}_{evolving_atom}({state_symb})_m={m}_{SAE_model}_L={L}_kmax={k_max}_N={N}_rmax={r_max}_Lmap={L_map}_dt={dt}.dat'
    else:
        evo_data_file = f'VEvo_nopt={time_step}_{evolving_atom}({state_symb})@C60_m={m}_{SAE_model}_{conf_model}_L={L}_kmax={k_max}_N={N}_rmax={r_max}_Lmap={L_map}_dt={dt}.dat'
else:
    evo_data_file = 'Evo_nopt=88036_H(1s)_m=0_SAE-M1_L=20_kmax=50_N=200_rmax=200_Lmap=80_dt=0.1.dat'

evo_data_path = this_dir.parent / 'Time_evolution_data' / f'{evo_data_file}'
evo_data = np.loadtxt(evo_data_path, skiprows=1)

t = evo_data[:, 0]                         # time                       : (a.u.)
E_t = evo_data[:, 1]                       # Electric field             : (a.u.)
dipole_moment = evo_data[:, 2]             # dipole moment d(t)         : (a.u.)
survival_probability = evo_data[:, 3]      # survival probability ps(t) : (a.u.)



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                    Calculating the HHG Spectra                     |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dipole_mom_FFT = ft.fft(dipole_moment)
freq_w = ft.fftfreq(len(t), d=dt) * 2 * np.pi                   # Nyquist Angular frequency (omega -> w).
dip_mom_power_spectra = np.abs(dipole_mom_FFT / tf)**2          # Harmonic power spectra.

positive_freq_mask = freq_w > 0             # positive angular frequency mask: returns a boolean array where True corresponds to freq_w > 0
freq_pos = freq_w[positive_freq_mask]       # Positive Nyquist frequencies.

harmonic_order = freq_pos / w0                                          # Harmonic Order (w/w0)
dip_mom_power_spectra = dip_mom_power_spectra[positive_freq_mask]       # P(w) : The power spectra you want!



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                       Conversion efficiency                        |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
harmonic_energy = np.trapezoid(dip_mom_power_spectra, freq_pos)
laser_energy = np.trapezoid(E_t**2, t)

eta = harmonic_energy / laser_energy

print(f" {WHITE}~~~~~~~~~~~: Harmonic Spectra Summary :~~~~~~~~~~{RESET}")
print(f" Number of time points (len(t))   : {len(t)}")
print(f" Time step (dt)                   : {dt} a.u.")
print(f" Fundamental frequency (ω₀)       : {w0:.5f} a.u.")
print(f" Max frequency (Nyquist, ω_max)   : {freq_pos[-1]:.5f} a.u.", '\n')

print(f" {WHITE}~~~~~~~~~~~~: Conversion efficiency :~~~~~~~~~~~~{RESET}")
print(f" Total laser energy (∫E² dt)      : {laser_energy:.6e}")
print(f" Total harmonic energy (∫P(ω) dω) : {harmonic_energy:.6e}")
print(f" Conversion efficiency (eta)      : {eta:.6e}")



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#              Attosecond pulse via spectral gating                  |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
accel_FFT = -(freq_w**2) * dipole_mom_FFT   # Dipole acceleration spectrum (physically radiated quantity)
harmonic_orders_full = freq_w / w0          # Harmonic order axis (signed, +/- branches)
t_over_T = t / T                            # precompute once, reused everywhere below

# Initial gate / GUI default values
harm_min_0, harm_max_0 = 11.0, 45.0
gate_order_0 = 20
t_min_T, t_max_T = float(t.min()/T), float(t.max()/T)
zoom_min_0, zoom_max_0 = t_min_T, t_max_T
num_gauss_0 = 3

# Soft-edged window (super-Gaussian) instead of a hard cutoff,
# to avoid ringing artifacts from an abrupt spectral edge.
# Evaluated on |freq_w|/w0 so it's symmetric for +/- frequencies,
# which keeps a_t_gated real after the inverse FFT.
def soft_gate(mask_freqs, lo, hi, order=6):
    center = (lo + hi) / 2
    width  = (hi - lo) / 2
    return np.exp(-((np.abs(mask_freqs) - center) / width)**order)

def compute_pulse(lo, hi, order):
    """Recompute gate + gated acceleration spectrum + attosecond pulse for given (lo, hi, order)."""
    gate = soft_gate(harmonic_orders_full, lo, hi, order)
    accel_gated = accel_FFT * gate
    a_t_gated = ft.ifft(accel_gated)
    intensity = np.abs(a_t_gated)**2
    intensity /= intensity.max()
    return gate, intensity

gate, attosecond_intensity = compute_pulse(harm_min_0, harm_max_0, gate_order_0)
gate_pos = gate[positive_freq_mask]         # Gate values on the positive-frequency axis (for overlay on HHG spectrum)


def gaussian_sum(x, *params):
    """Sum of N Gaussians: params = [A1, mu1, sigma1, A2, mu2, sigma2, ...]."""
    y = np.zeros_like(x)
    for A, mu, sigma in zip(params[0::3], params[1::3], params[2::3]):
        y += A * np.exp(-0.5 * ((x - mu) / sigma) ** 2)
    return y


# Try to maximize the plot window regardless of backend (best-effort, never fatal)
def _maximize_window(fig):
    try:
        mgr = fig.canvas.manager
        backend = plt.get_backend().lower()
        if 'qt' in backend:
            mgr.window.showMaximized()
        elif 'tk' in backend:
            mgr.window.state('zoomed')
        elif 'wx' in backend:
            mgr.frame.Maximize(True)
        else:
            mgr.full_screen_toggle()
    except Exception:
        pass



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                         Interactive Plotting                       |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fig1 = plt.figure(figsize=fig_size)
gs = fig1.add_gridspec(2, 1, top=0.94, bottom=0.08, left=0.07, right=0.70, hspace=0.20)

ax2 = fig1.add_subplot(gs[0])         # HHG spectra
ax2b = ax2.twinx()                    # Spectral selection gate (0-1, right axis)
ax7 = fig1.add_subplot(gs[1])         # Attosecond pulse intensity
da.decorate_2d([ax2, ax7])
da.decorate_2d(ax2b, visible_spine='none', grid=False)

spec_line, = ax2.plot(harmonic_order, np.log10(dip_mom_power_spectra), color='#2CA02C', label=r'log$_{10}$[P($\omega$)]')
gate_line,  = ax2b.plot(harmonic_order, gate_pos, color='dimgray', ls='--', lw=1.5)
atto_line,  = ax7.plot(t_over_T, attosecond_intensity, color='crimson', lw=1.5, label='Pulse intensity')
component_lines = []       # dynamically re-created each fit (one per Gaussian component)

# # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# #     Reference-phase markers: expected recombination times          |
# #     phi0 = omega0 * t0  ->  t0/T = phi0 / (2*pi), offset from a    |
# #     chosen reference optical cycle (here: 30.0)                    |
# # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# t_ref_cycle = 30.0                                  # the cycle you're calling t=0
# phi0_values = np.array([0.101, 1.1]) * np.pi        # given recombination phases
# t0_over_T   = t_ref_cycle + phi0_values / (2 * np.pi)

# marker_lines = []
# for phi0, tT in zip(phi0_values, t0_over_T):
#     ln = ax7.axvline(tT, color='black', ls=':', lw=1.3, alpha=0.85, zorder=5)
#     ax7.annotate(rf'$\phi_0={phi0/np.pi:.3f}\pi$', xy=(tT, 1.02), xycoords=('data', 'axes fraction'),
#                  ha='center', va='bottom', fontsize=8.5, rotation=90, clip_on=False)
#     marker_lines.append(ln)


ax2.set_yticks(np.arange(-20, -2, 4))                               # Some controls
ax2.set_xticks(np.arange(1, int(max(harmonic_order)), 4))           # over
ax2.set_xlim(-1, 102)                                                # HHG spectra plot.
ax2b.set_ylim(0, 1.05)
ax2b.set_yticks([])

ax2.set_xlabel(r'Harmonic Order (ω/ω$_0$)', fontsize=12)
ax2.set_ylabel(r'log$_{10}$[P($\omega$)]', fontsize=12)

ax7.set_xlabel('optical cycles (t/T)', fontsize=12)
ax7.set_ylabel('Attosecond pulse intensity (norm.)', fontsize=12)
ax7.set_xlim(zoom_min_0, zoom_max_0)
ax7.set_ylim(-0.05, 1.10)

ax2.legend(loc='upper right', fontsize=11, framealpha=0.5, edgecolor='w')
ax7.legend(loc='upper right', fontsize=11, framealpha=0.5, edgecolor='w')

fig1.suptitle(evo_data_file, fontsize=12)


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#              GUI controls (compact RHS textboxes + sliders)        |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rect_panel_x0 = 0.775                   # fixed anchor for the background rectangle (kept in place)
panel_x0, panel_w = 0.805, 0.117        # widgets/labels nudged right so they sit inside the rectangle
box_h, box_gap = 0.024, 0.044           # box height / vertical spacing

# Light background panel behind all controls, for visual grouping
fig1.add_artist(Rectangle((rect_panel_x0 - 0.05, 0.03), 0.25, 0.90,
                           transform=fig1.transFigure, facecolor='#f5f5f7',
                           edgecolor='#cccccc', linewidth=1.0, zorder=-1))

def pad(val):
    """Left-pad the displayed value so digits don't touch the textbox border."""
    return f'   {val}'

def add_labeled_box(y, label, initial):
    fig1.text(panel_x0 - 0.02, y + box_h/2, label, ha='right', va='center', fontsize=10)
    box_ax = fig1.add_axes([panel_x0, y, panel_w, box_h])
    return TextBox(box_ax, '', initial=pad(initial))

def section_header(y, text):
    fig1.text(panel_x0, y, text, fontsize=12, fontweight='bold')
    fig1.add_artist(plt.Line2D([panel_x0, panel_x0 + panel_w], [y - 0.008, y - 0.008],
                                transform=fig1.transFigure, color='#bbbbbb', lw=1.0))

# Section: spectral gate
y = 0.90
section_header(y, 'Spectral gate'); y -= box_gap
tb_harm_min = add_labeled_box(y, 'Harm. min',  harm_min_0);  y -= box_gap
tb_harm_max = add_labeled_box(y, 'Harm. max',  harm_max_0);  y -= box_gap
tb_order    = add_labeled_box(y, 'Smoothness', gate_order_0); y -= box_gap*1.6

# Section: pulse zoom (textboxes + a single self-narrowing slider underneath)
section_header(y, 'Pulse zoom (t/T)'); y -= box_gap
tb_zoom_min = add_labeled_box(y, 'Zoom min', f'{zoom_min_0:.3f}'); y -= box_gap
tb_zoom_max = add_labeled_box(y, 'Zoom max', f'{zoom_max_0:.3f}'); y -= box_gap*1.1

fig1.text(panel_x0, y + 0.014, 'Zoom', fontsize=8.5, color='#666666')
zoom_slider_pos = [panel_x0, y, panel_w, 0.016]
ax_zoom_slider = fig1.add_axes(zoom_slider_pos)
zoom_slider = RangeSlider(ax_zoom_slider, '', t_min_T, t_max_T, valinit=(zoom_min_0, zoom_max_0))
zoom_slider.valtext.set_visible(False)
y -= box_gap*1.6

# Section: Gaussian fitting
section_header(y, 'Gaussian fit (zoom)'); y -= box_gap
tb_num_gauss = add_labeled_box(y, '# of peaks', num_gauss_0); y -= box_gap*1.3

ax_fit = fig1.add_axes([panel_x0, y, panel_w, 0.032])
fit_button = Button(ax_fit, 'Fit Gaussians')
y -= box_gap*1.3

ax_apply = fig1.add_axes([panel_x0, y, panel_w*0.48, 0.032])
ax_reset = fig1.add_axes([panel_x0 + panel_w*0.52, y, panel_w*0.48, 0.032])
apply_button = Button(ax_apply, 'Apply')
reset_button = Button(ax_reset, 'Reset')
y -= box_gap*1.5

# Fit-results readout at the bottom of the panel
info_text = fig1.text(panel_x0 - 0.02, y, '', ha='left', va='top', fontsize=11,
                       family=['Courier New', 'DejaVu Sans Mono', 'monospace'], linespacing=1.6)


def _to_float(textbox, fallback):
    try:
        return float(textbox.text)         # float() tolerates the leading padding spaces
    except ValueError:
        textbox.set_val(pad(fallback))     # revert invalid entry
        return fallback


def _to_int(textbox, fallback, lo=1, hi=8):
    try:
        val = int(round(float(textbox.text)))
        return min(max(val, lo), hi)
    except ValueError:
        textbox.set_val(pad(fallback))
        return fallback


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     Split, cost-aware callbacks: only recompute what actually       |
#     changed, so slider dragging / textbox edits stay responsive.    |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def update_gate(_event=None):
    """Expensive: re-runs the FFT-based gating pipeline. Only call on gate-param changes."""
    global attosecond_intensity
    lo    = _to_float(tb_harm_min, harm_min_0)
    hi    = _to_float(tb_harm_max, harm_max_0)
    order = _to_float(tb_order, gate_order_0)

    gate, attosecond_intensity = compute_pulse(lo, hi, order)
    gate_line.set_ydata(gate[positive_freq_mask])
    atto_line.set_ydata(attosecond_intensity)
    fig1.canvas.draw_idle()


def rebuild_zoom_slider(lo, hi):
    """Re-create the zoom slider's own range to span exactly its current selection window.
    This makes the single slider self-narrowing: every drag becomes the new full range of
    the handles, so repeated dragging lets you zoom in progressively finer without needing
    a separate 'fine' slider."""
    global zoom_slider, ax_zoom_slider
    if hi <= lo:
        hi = lo + 1e-6
    ax_zoom_slider.remove()
    ax_zoom_slider = fig1.add_axes(zoom_slider_pos)
    zoom_slider = RangeSlider(ax_zoom_slider, '', lo, hi, valinit=(lo, hi))
    zoom_slider.valtext.set_visible(False)
    zoom_slider.on_changed(sync_zoom_from_slider)
    fig1.canvas.draw_idle()


def update_zoom(_event=None):
    """Cheap: only changes the pulse-axis x-limits."""
    zlo = _to_float(tb_zoom_min, zoom_min_0)
    zhi = _to_float(tb_zoom_max, zoom_max_0)
    ax7.set_xlim(zlo, zhi)
    fig1.canvas.draw_idle()


def sync_zoom_from_slider(val):
    """Slider drag -> push values into textboxes, redraw xlim, and rebuild the slider's own
    range to match the current window so the next drag zooms in even finer."""
    zlo, zhi = val
    tb_zoom_min.eventson, tb_zoom_max.eventson = False, False
    tb_zoom_min.set_val(pad(f'{zlo:.3f}'))
    tb_zoom_max.set_val(pad(f'{zhi:.3f}'))
    tb_zoom_min.eventson, tb_zoom_max.eventson = True, True
    ax7.set_xlim(zlo, zhi)
    rebuild_zoom_slider(zlo, zhi)


def sync_zoom_from_textbox(_event=None):
    """Textbox edit -> push values into the slider (without recursing), redraw xlim, and
    rebuild the slider's own range to match."""
    zlo = _to_float(tb_zoom_min, zoom_min_0)
    zhi = _to_float(tb_zoom_max, zoom_max_0)
    ax7.set_xlim(zlo, zhi)
    rebuild_zoom_slider(zlo, zhi)


def clear_component_lines():
    global component_lines
    for ln in component_lines:
        ln.remove()
    component_lines = []


def fit_gaussians(_event=None):
    """Detect the n most prominent distinct peaks in the current zoom window
    (ignoring low-amplitude ringing) and fit a sum of n Gaussians to them."""
    global component_lines

    n = _to_int(tb_num_gauss, num_gauss_0, lo=1, hi=8)
    zlo, zhi = ax7.get_xlim()
    mask = (t_over_T >= zlo) & (t_over_T <= zhi)
    x = t_over_T[mask]
    y = attosecond_intensity[mask]

    if x.size < 5:
        info_text.set_text('Zoom window too narrow to fit.')
        fig1.canvas.draw_idle()
        return

    # Peak detection: prominence + height filters out low-amplitude ringing,
    # keeping only the visually distinct bursts.
    peaks, props = find_peaks(y, prominence=0.15 * y.max(), height=0.2 * y.max())

    if peaks.size == 0:
        info_text.set_text('No distinct peaks found.\nTry widening the zoom, or\nlower "# of peaks".')
        clear_component_lines()
        fig1.canvas.draw_idle()
        return

    # Keep the n most prominent peaks, then order them left-to-right for reporting
    order_by_prom = np.argsort(props['prominences'])[::-1][:n]
    chosen = np.sort(peaks[order_by_prom])
    n_fit = len(chosen)

    # Initial guesses: amplitude/position from the detected peak, width from local spacing
    span = zhi - zlo
    sigma_guess = max(span / (12 * n_fit), 3 * (x[1] - x[0]))
    p0, lower, upper = [], [], []
    for idx in chosen:
        A0, mu0 = y[idx], x[idx]
        p0 += [A0, mu0, sigma_guess]
        lower += [0.0, zlo, (x[1] - x[0])]
        upper += [1.5, zhi, span / 2]

    try:
        popt, _ = curve_fit(gaussian_sum, x, y, p0=p0, bounds=(lower, upper), maxfev=20000)
    except RuntimeError:
        info_text.set_text('Fit did not converge —\ntry adjusting the zoom.')
        fig1.canvas.draw_idle()
        return

    x_dense = np.linspace(zlo, zhi, 2000)

    # Plot each Gaussian component in its own vibrant, high-contrast color (no sum curve)
    clear_component_lines()
    triplets = sorted(zip(popt[0::3], popt[1::3], popt[2::3]), key=lambda p: p[1])  # sort by position
    for i, (A, mu, sigma) in enumerate(triplets):
        color = GAUSS_COLORS[i % len(GAUSS_COLORS)]
        ln, = ax7.plot(x_dense, A * np.exp(-0.5 * ((x_dense - mu) / sigma) ** 2),
                        color=color, lw=2.4, alpha=0.95, label=f'Peak {i+1}')
        component_lines.append(ln)

    # ~~~ Report position (t/T) and FWHM (attoseconds) for each fitted peak ~~~
    lines = [f'Fit results ({n_fit} peak{"s" if n_fit > 1 else ""}):']
    for i, (A, mu, sigma) in enumerate(triplets, start=1):
        fwhm_as = 2 * np.sqrt(2 * np.log(2)) * sigma * T * AU_TO_AS
        lines.append(f'  #{i}  pos  = {mu:8.4f} (t/T)')
        lines.append(f'      FWHM = {fwhm_as:9.2f} as')
    info_text.set_text('\n'.join(lines))

    ax7.legend(loc='upper right', fontsize=9.5, framealpha=0.5, edgecolor='w', ncol=1)
    fig1.canvas.draw_idle()


def apply_all(_event=None):
    update_gate()
    update_zoom()


def reset(_event=None):
    tb_harm_min.set_val(pad(harm_min_0))
    tb_harm_max.set_val(pad(harm_max_0))
    tb_order.set_val(pad(gate_order_0))
    tb_zoom_min.set_val(pad(f'{zoom_min_0:.3f}'))
    tb_zoom_max.set_val(pad(f'{zoom_max_0:.3f}'))
    rebuild_zoom_slider(zoom_min_0, zoom_max_0)
    tb_num_gauss.set_val(pad(num_gauss_0))
    clear_component_lines()
    info_text.set_text('')
    ax7.legend(loc='upper right', fontsize=11, framealpha=0.5, edgecolor='w')
    apply_all()


# Each control only triggers the callback that actually needs to run
tb_harm_min.on_submit(update_gate)
tb_harm_max.on_submit(update_gate)
tb_order.on_submit(update_gate)

tb_zoom_min.on_submit(sync_zoom_from_textbox)
tb_zoom_max.on_submit(sync_zoom_from_textbox)
zoom_slider.on_changed(sync_zoom_from_slider)

fit_button.on_clicked(fit_gaussians)
apply_button.on_clicked(apply_all)
reset_button.on_clicked(reset)

apply_all()   # draw everything once at startup
_maximize_window(fig1)

plt.show()